# Generated by Django 4.0.3 on 2022-03-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_alter_class_number_alter_semester_semester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='dob',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='lecturer',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='lecturer',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dob',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='enrolTime',
            new_name='enrollTime',
        ),
    ]
