# Generated by Django 4.0.4 on 2022-05-12 03:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gradebook', '0004_rename_dob_lecturer_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='staffID',
            field=models.PositiveIntegerField(default=10001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(to='gradebook.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='studentID',
            field=models.PositiveIntegerField(default=10001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], default='S1', max_length=2),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2200)]),
        ),
    ]
