# Generated by Django 4.0.4 on 2022-05-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0005_lecturer_staffid_lecturer_user_semester_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gradebook.lecturer'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='staffID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='gradebook.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
