# Generated by Django 4.0.4 on 2022-05-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0006_alter_class_lecturer_alter_lecturer_staffid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentEnrollment',
            new_name='StudentEnrolment',
        ),
    ]
