# Generated by Django 4.0.4 on 2022-05-12 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0007_rename_studentenrollment_studentenrolment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrolment',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
